### PR TITLE
Security recommendation from snyk: package upgrades 

### PR DESCRIPTION
**Pull request by MichaelCollinsAmido**
📲 What
Upgraded next@9.5.2 to next@11.1.0
Upgraded axios@0.21.1 to axios@0.21.3
Upgraded ioredis@4.27.5 to ioredis@4.27.8
Upgraded contentful@7.14.6 to contentful@8.0.3

🤔 Why
To resolve vulnerabilities [Snyk].

👀 Evidence
image
Tested locally 
image

🕵️ How to test
Need to run in pipeline for further testing

✅ Acceptance criteria Checklist
 Code peer reviewed?
 Documentation has been updated to reflect the changes?
 Passing all automated tests, including a successful deployment?
 Passing any exploratory testing?
 Rebased/merged with latest changes from development and re-tested?
 Meeting the Coding Standards?

### CODE REVIEW

**Comment by ElvenSpellmaker** [comment]
@RichardSlater You need to enable build PRs for forks in Azure DevOps, which is now safer because we've enabled comment to build

**Comment by RichardSlater** [comment]
> @RichardSlater You need to enable build PRs for forks in Azure DevOps, which is now safer because we've enabled comment to build

What's confusing me is this worked 8 days ago...

**Comment by ElvenSpellmaker** [comment]
> > @RichardSlater You need to enable build PRs for forks in Azure DevOps, which is now safer because we've enabled comment to build
> 
> What's confusing me is this worked 8 days ago...

Was that PR from a fork?

**Comment by RichardSlater** [comment]
[Looks that way](https://github.com/amido/stacks-typescript-ssr/pull/171) yes.

**Comment by RichardSlater** [comment]
image
image
Middle checkbox maybe @ElvenSpellmaker

**Comment by ElvenSpellmaker** [comment]
Yeah, it might need all three to access the library vars etc

**Comment by RichardSlater** [comment]
I've tried minimal first, see how that pans out.

**Comment by RichardSlater** [comment]
at a minimum it needs **Make secrets available to builds of forks** in addition to being able to build.

**Comment by RichardSlater** [comment]
looks like we need **Make fork builds have the same permissions as regular builds** too.

**Comment by RichardSlater** [comment]
@MichaelCollinsAmido we managed to fix the automated trigger of builds when you type `/azp run` however it's failing with what appears to be typescript validation errors in 3rd party components which might require excluding something from a check rather than fixing anything.

**Pull request merged**
